# Generated by Django 5.0.8 on 2024-08-31 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payments_balance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.balance'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(help_text='If specified, the order will be processed', on_delete=django.db.models.deletion.CASCADE, related_name='payments_transactions', to='core.order'),
        ),
    ]
