# Generated by Django 5.0.8 on 2024-09-02 03:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibes_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_token',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='activation token'),
        ),
    ]
