# Generated by Django 5.1.5 on 2025-03-10 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_blacklist', '0012_alter_outstandingtoken_user'),
        ('vibes_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedToken',
            fields=[
            ],
            options={
                'verbose_name': 'blacklisted token',
                'verbose_name_plural': 'blacklisted tokens',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('token_blacklist.blacklistedtoken',),
        ),
        migrations.CreateModel(
            name='OutstandingToken',
            fields=[
            ],
            options={
                'verbose_name': 'outstanding token',
                'verbose_name_plural': 'outstanding tokens',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('token_blacklist.outstandingtoken',),
        ),
    ]
