# Generated by Django 5.2 on 2025-05-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vibes_auth', '0002_blacklistedtoken_outstandingtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(
                choices=[('en-gb', 'English (British)'), ('ar-ar', 'العربية'), ('cs-cz', 'Česky'), ('da-dk', 'Dansk'),
                         ('de-de', 'Deutsch'), ('en-us', 'English (American)'), ('es-es', 'Español'),
                         ('fr-fr', 'Français'), ('hi-in', 'हिंदी'), ('it-it', 'Italiano'), ('ja-jp', '日本語'),
                         ('kk-kz', 'Қазақ'), ('nl-nl', 'Nederlands'), ('pl-pl', 'Polska'), ('pt-br', 'Português'),
                         ('ro-ro', 'Română'), ('ru-ru', 'Русский'), ('zh-hans', '简体中文')], default='en-gb',
                max_length=7),
        ),
    ]
