services:
  app:
    restart: always
    build: .
    command: >
      sh -c "poetry run python manage.py await_services &&
             if [ \"$DEBUG\" = \"1\" ]; then
               poetry run gunicorn evibes.wsgi:application --bind 0.0.0.0:8000 --workers 2 --log-level debug --reload;
             else
               poetry run gunicorn evibes.wsgi:application --bind 0.0.0.0:8000 --workers 12 --timeout 120;
             fi"
    volumes:
      - .:/app
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - database

  database:
    restart: always
    image: postgis/postgis:latest
    volumes:
      - ./services_data/postgres:/var/lib/postgresql/data/
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      .env

  worker:
    restart: always
    build: .
    command: sh -c "poetry run celery -A evibes worker --loglevel=info --autoscale=10,3"
    volumes:
      - .:/app
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - .env
    depends_on:
      - app
      - redis

  beat:
    restart: always
    build: .
    command: sh -c "poetry run celery -A evibes beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    volumes:
      - .:/app
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - .env
    depends_on:
      - worker

  redis:
    restart: always
    volumes:
      - ./services_data/redis:/data
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    image: redis:latest
    ports:
      - "6379:6379"