# Official website https://docs.astral.sh/ruff/
# This config for Ruff v.0.5.1+

line-length = 120
target-version = "py38"
exclude = [
    "migrations",
    "media",
    "static",
    "storefront",
]

[lint]
select = [
    "E",
    "W",
    "F",
    "B",
    "I",
    "RUF",
    "UP",
    "N",
    "A",
    "COM",
    "C4",
    "DJ001",
    "RSE",
    "SIM",
    "ISC",
    "TID252",
    "PGH004",
]

ignore = [
    "B904",
    "RUF001",
    "RUF002",
    "RUF003",
    "RUF005",
    "RUF012",
    "A003",
    "A002",
    "COM812",
    "S603",
]

[lint.per-file-ignores]
"__init__.py" = ["E402", "F401"]

[format]
quote-style = "double"
indent-style = "space"
