# Generated by Django 5.0.8 on 2024-08-31 01:58

import core.models
import core.utils
import core.validators
import django.core.validators
import django.db.models.deletion
import django_extensions.db.fields
import mptt.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeGroup',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(help_text="Attribute group's name", max_length=255)),
                ('name_ru', models.CharField(blank=True, help_text="Attribute group's name in Russian", max_length=255, null=True)),
                ('name_de', models.CharField(blank=True, help_text="Attribute group's name in German", max_length=255, null=True)),
                ('name_it', models.CharField(blank=True, help_text="Attribute group's name in Italian", max_length=255, null=True)),
                ('name_es', models.CharField(blank=True, help_text="Attribute group's name in Spanish", max_length=255, null=True)),
                ('name_nl', models.CharField(blank=True, help_text="Attribute group's name in Dutch", max_length=255, null=True)),
                ('name_fr', models.CharField(blank=True, help_text="Attribute group's name in French", max_length=255, null=True)),
                ('name_ro', models.CharField(blank=True, help_text="Attribute group's name in Romanian", max_length=255, null=True)),
                ('name_pl', models.CharField(blank=True, help_text="Attribute group's name in Polish", max_length=255, null=True)),
                ('name_cs', models.CharField(blank=True, help_text="Attribute group's name in Czech", max_length=255, null=True)),
                ('name_da', models.CharField(blank=True, help_text="Attribute group's name in Danish", max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'attribute group',
                'verbose_name_plural': 'attribute groups',
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('authentication', models.JSONField(blank=True, help_text="Authentication info for dealer's endpoints", null=True, verbose_name='authentication')),
                ('markup_percent', models.IntegerField(default=0, help_text="The markup applied to parsed products. Categories' markups have higher priority", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='markup')),
                ('name', models.CharField(help_text="Dealer's name", max_length=255, verbose_name='dealer name')),
            ],
            options={
                'verbose_name': 'dealer',
                'verbose_name_plural': 'dealers',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('comment', models.TextField(blank=True, help_text="Feedback's text", null=True, verbose_name='comment')),
                ('rating', models.FloatField(blank=True, help_text="Feedback's rating", null=True, verbose_name='rating')),
            ],
            options={
                'verbose_name': 'feedback',
                'verbose_name_plural': 'feedbacks',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('FAILED', 'failed'), ('PAYMENT', 'payment'), ('FINISHED', 'finished')], default='PENDING', help_text="Order's status", max_length=64, verbose_name='status')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('buy_price', models.FloatField(blank=True, help_text='The price the customer paid when bought the order', null=True, verbose_name='buy price')),
                ('comments', models.TextField(blank=True, help_text="Order-product's comments. Visible only to admins", null=True, verbose_name='comments')),
                ('notifications', models.JSONField(blank=True, help_text="Order-product's notifications. Displayed to user's on the storefront", null=True, verbose_name='notifications')),
                ('status', models.CharField(blank=True, choices=[('FINISHED', 'finished'), ('DELIVERING', 'delivering'), ('DELIVERED', 'delivered'), ('CANCELED', 'canceled'), ('FAILED', 'failed'), ('PENDING', 'pending'), ('ACCEPTED', 'accepted')], help_text="Order-product's status", max_length=128, null=True, verbose_name='status')),
            ],
            options={
                'verbose_name': 'order product',
                'verbose_name_plural': 'order products',
            },
        ),
        migrations.CreateModel(
            name='PredefinedAttributes',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'verbose_name': 'predefined attribute',
                'verbose_name_plural': 'predefined attributes',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('attributes', models.JSONField(blank=True, help_text="Product's attributes", null=True, verbose_name='attributes')),
                ('description', models.TextField(blank=True, help_text="Product's description", null=True, verbose_name='description')),
                ('name', models.CharField(help_text="Product's name", max_length=255, verbose_name='name')),
                ('tags', models.TextField(blank=True, help_text="Product's tags is a comma-separated list", verbose_name='tags')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(help_text="Product attribute's name", max_length=255, verbose_name='name')),
                ('name_ru', models.CharField(blank=True, help_text="Product attribute's name in Russian", max_length=255, null=True, verbose_name='name in russian')),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean')], help_text="Product attribute's value type", max_length=50, verbose_name='value type')),
            ],
            options={
                'verbose_name': 'product attribute',
                'verbose_name_plural': 'product attributes',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('alt', models.CharField(help_text="Image's alt text", max_length=255, verbose_name='alt')),
                ('image', models.ImageField(help_text='Image', upload_to=core.models.ProductImage.get_product_uuid_as_path, verbose_name='image')),
                ('priority', models.IntegerField(default=0, help_text="Image's priority. 1 means the first displayed image", validators=[django.core.validators.MinValueValidator(1)], verbose_name='priority')),
            ],
            options={
                'verbose_name': 'product image',
                'verbose_name_plural': 'product images',
                'ordering': ('priority',),
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('code', models.CharField(default=core.utils.get_random_code, help_text="Promocode's code", max_length=20, unique=True, verbose_name='promo code')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text="Promocode's discount amount. May be set only if 'discount percent' is empty", max_digits=10, null=True, verbose_name='discount amount')),
                ('discount_percent', models.IntegerField(blank=True, help_text="Promocode's discount percent. May be set only if 'discount amount' is empty", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='discount percent')),
                ('end_time', models.DateTimeField(blank=True, help_text="Promocode's end time", null=True, verbose_name='end time')),
                ('start_time', models.DateTimeField(blank=True, help_text="Promocode's start time", null=True, verbose_name='start time')),
                ('used_on', models.DateTimeField(blank=True, help_text="Promocode's date of usage. If empty - Promocode was not used", null=True, verbose_name='used on')),
            ],
            options={
                'verbose_name': 'promo code',
                'verbose_name_plural': 'promo codes',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('discount_percent', models.IntegerField(help_text="Promotion's discount percent", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Discount Percent')),
                ('name', models.CharField(help_text="Promotion's name", max_length=256, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'promotion',
                'verbose_name_plural': 'promotions',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('price', models.FloatField(default=0.0, help_text="Product's price after applying the markup", verbose_name='price')),
                ('purchase_price', models.FloatField(default=0.0, help_text="Product's purchase_price from dealer's endpoint", verbose_name='purchase price')),
                ('quantity', models.IntegerField(default=0, help_text="Product's quantity in dealer's stock", verbose_name='quantity')),
                ('sku', models.CharField(help_text="Dealer's SKU", max_length=255, verbose_name='sku')),
            ],
            options={
                'verbose_name': 'stock',
                'verbose_name_plural': 'stocks',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'verbose_name': 'wishlist',
                'verbose_name_plural': 'wishlists',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('image', models.ImageField(help_text="Category's image", null=True, upload_to=core.validators.validate_category_image_dimensions, verbose_name='image')),
                ('markup_percent', models.IntegerField(default=0, help_text="The markup applied to parsed products. Dealers' markups have lower priority", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='markup')),
                ('name', models.CharField(help_text="Category's name in Russian", max_length=255, verbose_name='name')),
                ('name_ru', models.CharField(help_text="Category's name in Russian", max_length=255, verbose_name='name')),
                ('name_de', models.CharField(help_text="Category's name in German", max_length=255, verbose_name='name')),
                ('name_it', models.CharField(help_text="Category's name in Italian", max_length=255, verbose_name='name')),
                ('name_es', models.CharField(help_text="Category's name in Spanish", max_length=255, verbose_name='name')),
                ('name_nl', models.CharField(help_text="Category's name in Dutch", max_length=255, verbose_name='name')),
                ('name_fr', models.CharField(help_text="Category's name in French", max_length=255, verbose_name='name')),
                ('name_ro', models.CharField(help_text="Category's name in Romanian", max_length=255, verbose_name='name')),
                ('name_pl', models.CharField(help_text="Category's name in Polish", max_length=255, verbose_name='name')),
                ('name_cs', models.CharField(help_text="Category's name in Czech", max_length=255, verbose_name='name')),
                ('name_da', models.CharField(help_text="Category's name in Danish", max_length=255, verbose_name='name')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text="Category's parent", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.category', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='LocalizedAttribute',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('value', models.CharField(help_text="Localized attribute's value", max_length=255, verbose_name='value')),
                ('value_ru', models.CharField(blank=True, help_text="Localized attribute's value in Russian", max_length=255, null=True, verbose_name='value in russian')),
                ('value_de', models.CharField(blank=True, help_text="Localized attribute's value in German", max_length=255, null=True, verbose_name='value in russian')),
                ('value_it', models.CharField(blank=True, help_text="Localized attribute's value in Italian", max_length=255, null=True, verbose_name='value in russian')),
                ('value_es', models.CharField(blank=True, help_text="Localized attribute's value in Spanish", max_length=255, null=True, verbose_name='value in russian')),
                ('value_nl', models.CharField(blank=True, help_text="Localized attribute's value in Dutch", max_length=255, null=True, verbose_name='value in russian')),
                ('value_fr', models.CharField(blank=True, help_text="Localized attribute's value in French", max_length=255, null=True, verbose_name='value in russian')),
                ('value_ro', models.CharField(blank=True, help_text="Localized attribute's value in Romanian", max_length=255, null=True, verbose_name='value in russian')),
                ('value_pl', models.CharField(blank=True, help_text="Localized attribute's value in Polish", max_length=255, null=True, verbose_name='value in russian')),
                ('value_cs', models.CharField(blank=True, help_text="Localized attribute's value in Czech", max_length=255, null=True, verbose_name='value in russian')),
                ('value_da', models.CharField(blank=True, help_text="Localized attribute's value in Danish", max_length=255, null=True, verbose_name='value in russian')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text="Category's parent", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.localizedattribute', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'localized attribute',
                'verbose_name_plural': 'localized attributes',
            },
        ),
    ]
