# Generated by Django 5.1.3 on 2024-11-14 08:03

import core.utils
import core.validators
import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import django_extensions.db.fields
import mptt.fields
import parler.fields
import parler.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeGroup',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'verbose_name': 'attribute group',
                'verbose_name_plural': 'attribute groups',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('comment', models.TextField(blank=True, help_text="Feedback's text", null=True, verbose_name='comment')),
                ('rating', models.FloatField(blank=True, help_text="Feedback's rating", null=True, verbose_name='rating')),
            ],
            options={
                'verbose_name': 'feedback',
                'verbose_name_plural': 'feedbacks',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('FAILED', 'failed'), ('PAYMENT', 'payment'), ('CREATED', 'created'), ('DELIVERING', 'delivering'), ('FINISHED', 'finished')], default='PENDING', help_text="Order's status", max_length=64, verbose_name='status')),
                ('buy_time', models.DateTimeField(blank=True, default=None, help_text="Order's buy time", null=True, verbose_name='buy time')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('buy_price', models.FloatField(blank=True, help_text='The price the customer paid when bought the order', null=True, verbose_name='buy price')),
                ('comments', models.TextField(blank=True, help_text="Order-product's comments. Visible only to admins", null=True, verbose_name='comments')),
                ('notifications', models.JSONField(blank=True, help_text="Order-product's notifications. Displayed to user's on the storefront", null=True, verbose_name='notifications')),
                ('attributes', models.JSONField(blank=True, help_text="Order-product's notifications. Displayed to user's on the storefront", null=True, verbose_name='notifications')),
                ('quantity', models.PositiveIntegerField(default=1, help_text="Order-product's quantity")),
                ('status', models.CharField(choices=[('FINISHED', 'finished'), ('DELIVERING', 'delivering'), ('DELIVERED', 'delivered'), ('CANCELED', 'canceled'), ('FAILED', 'failed'), ('PENDING', 'pending'), ('ACCEPTED', 'accepted')], default='PENDING', help_text="Order-product's status", max_length=128, verbose_name='status')),
            ],
            options={
                'verbose_name': 'order product',
                'verbose_name_plural': 'order products',
            },
        ),
        migrations.CreateModel(
            name='PredefinedAttributes',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'verbose_name': 'predefined attribute',
                'verbose_name_plural': 'predefined attributes',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean')], help_text="Product attribute's value type", max_length=50, verbose_name='value type')),
            ],
            options={
                'verbose_name': 'product attribute',
                'verbose_name_plural': 'product attributes',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductAttributeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(help_text="Product attribute's name", max_length=255, verbose_name='name')),
                ('value', models.CharField(help_text="Localized attribute's value", max_length=255, verbose_name='value')),
                ('description', models.TextField(blank=True, help_text="Category's description", null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'product attribute Translation',
                'db_table': 'core_productattribute_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'verbose_name': 'product attribute value',
                'verbose_name_plural': 'product attribute values',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('alt', models.CharField(help_text="Image's alt text", max_length=255, verbose_name='alt')),
                ('image', models.ImageField(help_text='Image', upload_to=core.utils.get_product_uuid_as_path, verbose_name='image')),
                ('priority', models.IntegerField(default=1, help_text="Image's priority. 1 means the first displayed image", validators=[django.core.validators.MinValueValidator(1)], verbose_name='priority')),
            ],
            options={
                'verbose_name': 'product image',
                'verbose_name_plural': 'product images',
                'ordering': ('priority',),
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('tag_name', models.CharField(max_length=255)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductTagTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(help_text="Product's name", max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'product tag Translation',
                'db_table': 'core_producttag_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(help_text="Product's name", max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text="Product's description", null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'product Translation',
                'db_table': 'core_product_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('code', models.CharField(default=core.utils.get_random_code, help_text="Promocode's code", max_length=20, unique=True, verbose_name='promo code')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text="Promocode's discount amount. May be set only if 'discount percent' is empty", max_digits=10, null=True, verbose_name='discount amount')),
                ('discount_percent', models.IntegerField(blank=True, help_text="Promocode's discount percent. May be set only if 'discount amount' is empty", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='discount percent')),
                ('end_time', models.DateTimeField(blank=True, help_text="Promocode's end time", null=True, verbose_name='end time')),
                ('start_time', models.DateTimeField(blank=True, help_text="Promocode's start time", null=True, verbose_name='start time')),
                ('used_on', models.DateTimeField(blank=True, help_text="Promocode's date of usage. If empty - Promocode was not used", null=True, verbose_name='used on')),
            ],
            options={
                'verbose_name': 'promo code',
                'verbose_name_plural': 'promo codes',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('discount_percent', models.IntegerField(help_text="Promotion's discount percent", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Discount Percent')),
                ('name', models.CharField(help_text="Promotion's name", max_length=256, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'promotion',
                'verbose_name_plural': 'promotions',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('price', models.FloatField(default=0.0, help_text="Product's price after applying the markup", verbose_name='price')),
                ('purchase_price', models.FloatField(default=0.0, help_text="Product's purchase_price from dealer's endpoint", verbose_name='purchase price')),
                ('quantity', models.IntegerField(default=0, help_text="Product's quantity in dealer's stock", verbose_name='quantity')),
                ('sku', models.CharField(help_text="Dealer's SKU", max_length=255, verbose_name='sku')),
            ],
            options={
                'verbose_name': 'stock',
                'verbose_name_plural': 'stocks',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'verbose_name': 'wishlist',
                'verbose_name_plural': 'wishlists',
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean')], help_text="Attribute's value type", max_length=50, verbose_name='value type')),
                ('group', models.ForeignKey(help_text="Attribute's group", on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='core.attributegroup', verbose_name='group')),
            ],
            options={
                'verbose_name': 'attribute',
                'verbose_name_plural': 'attributes',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AttributeGroupTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(help_text="Attribute Group's name", max_length=255, verbose_name='name')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.attributegroup')),
            ],
            options={
                'verbose_name': 'attribute group Translation',
                'db_table': 'core_attributegroup_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AttributeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(help_text="Attribute's name", max_length=255, verbose_name='name')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.attribute')),
            ],
            options={
                'verbose_name': 'attribute Translation',
                'db_table': 'core_attribute_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('attribute', models.ForeignKey(help_text='Attribute', on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core.attribute', verbose_name='attribute')),
            ],
            options={
                'verbose_name': 'attribute value',
                'verbose_name_plural': 'attribute values',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AttributeValueTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('value', models.CharField(help_text='Attribute value', max_length=255, verbose_name='value')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.attributevalue')),
            ],
            options={
                'verbose_name': 'attribute value Translation',
                'db_table': 'core_attributevalue_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('image', models.ImageField(help_text="Category's image", null=True, upload_to='categories/', validators=[core.validators.validate_category_image_dimensions], verbose_name='image')),
                ('markup_percent', models.IntegerField(default=0, help_text="The markup applied to parsed products. Dealers' markups have lower priority", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='markup')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text="Category's parent", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.category', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(help_text="Brand's name", max_length=255, verbose_name='name')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.category')),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
            },
        ),
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorized_attributes', to='core.attribute')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_attributes', to='core.category')),
            ],
            options={
                'verbose_name': 'category attribute',
                'verbose_name_plural': 'category attributes',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='attributes',
            field=models.ManyToManyField(help_text='Attributes associated with the category', related_name='categories', through='core.CategoryAttribute', to='core.attribute', verbose_name='attributes'),
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(help_text="Category's name", max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text="Category's description", null=True, verbose_name='description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.category')),
            ],
            options={
                'verbose_name': 'category Translation',
                'db_table': 'core_category_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('authentication', models.JSONField(blank=True, help_text="Authentication info for dealer's endpoints", null=True, verbose_name='authentication')),
                ('markup_percent', models.IntegerField(default=0, help_text="The markup applied to parsed products. Categories' markups have higher priority", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='markup')),
                ('name', models.CharField(help_text="Dealer's name", max_length=255, verbose_name='dealer name')),
            ],
            options={
                'verbose_name': 'dealer',
                'verbose_name_plural': 'dealers',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['authentication'], name='core_dealer_authent_3fd9f3_gin')],
            },
        ),
    ]
