# Generated by Django 5.0.8 on 2024-08-31 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, help_text="Order's billing address", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_address_order', to='geo.address', verbose_name='billing address'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, help_text="Order's shipping address", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address_order', to='geo.address', verbose_name='shipping address'),
        ),
    ]
