# Generated by Django 5.0.8 on 2024-08-31 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(help_text="Order's user", on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(help_text='Order', on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='core.order', verbose_name='order'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='order_product',
            field=models.ForeignKey(blank=True, help_text="Feedback's product", null=True, on_delete=django.db.models.deletion.CASCADE, to='core.orderproduct', verbose_name='order product'),
        ),
        migrations.AddField(
            model_name='predefinedattributes',
            name='category',
            field=models.OneToOneField(help_text='Predefined attributes for category', on_delete=django.db.models.deletion.CASCADE, related_name='predefined_attributes', to='core.category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='predefinedattributes',
            name='groups',
            field=models.ManyToManyField(help_text='Predefined attribute groups for category', related_name='categories', to='core.attributegroup', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text="Product's categories", on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='categories'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='group',
            field=models.ForeignKey(help_text="Product attribute's group", on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='core.attributegroup', verbose_name='group'),
        ),
        migrations.AddField(
            model_name='localizedattribute',
            name='attribute',
            field=models.OneToOneField(help_text='Localized attribute', on_delete=django.db.models.deletion.CASCADE, related_name='localizations', to='core.productattribute', verbose_name='attribute'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(help_text='Product', on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, help_text="Product's images", related_name='related_images', to='core.productimage', verbose_name='images'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Users which may use this Promocode', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, help_text="Order's promo code. May be empty. Do not change after 'finished' status", null=True, on_delete=django.db.models.deletion.PROTECT, to='core.promocode', verbose_name='promo code'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='products',
            field=models.ManyToManyField(blank=True, help_text="Promotion's products", to='core.product', verbose_name='products'),
        ),
        migrations.AddField(
            model_name='stock',
            name='dealer',
            field=models.ForeignKey(help_text='Dealer', on_delete=django.db.models.deletion.CASCADE, to='core.dealer', verbose_name='dealer'),
        ),
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(help_text='Product', on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='products',
            field=models.ManyToManyField(blank=True, help_text="User's wishlisted products", to='core.product', verbose_name='products'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.OneToOneField(blank=True, help_text='User', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_related_wishlist', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
