# Generated by Django 5.1.3 on 2024-11-14 08:03

import django.contrib.postgres.indexes
import django.db.models.deletion
import parler.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(help_text="Order's user", on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(help_text='Order', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='core.order', verbose_name='order'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='order_product',
            field=models.OneToOneField(help_text="Feedback's product", on_delete=django.db.models.deletion.CASCADE, to='core.orderproduct', verbose_name='order product'),
        ),
        migrations.AddField(
            model_name='predefinedattributes',
            name='category',
            field=models.OneToOneField(help_text='Predefined attributes for category', on_delete=django.db.models.deletion.CASCADE, related_name='predefined_attributes', to='core.category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='predefinedattributes',
            name='groups',
            field=models.ManyToManyField(help_text='Predefined attribute groups for category', related_name='categories', to='core.attributegroup', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, help_text="Product's brand", null=True, on_delete=django.db.models.deletion.CASCADE, to='core.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text="Product's category", on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='group',
            field=models.ForeignKey(help_text="Product attribute's group", on_delete=django.db.models.deletion.CASCADE, related_name='self_attributes', to='core.attributegroup', verbose_name='group'),
        ),
        migrations.AddField(
            model_name='productattributetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.productattribute'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='attribute_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.attributevalue'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(related_name='products', through='core.ProductAttributeValue', to='core.attributevalue', verbose_name='attributes'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(help_text='Product', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text="Product's tags", to='core.producttag', verbose_name='tags'),
        ),
        migrations.AddField(
            model_name='producttagtranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.producttag'),
        ),
        migrations.AddField(
            model_name='producttranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.product'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Users which may use this Promocode', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, help_text="Order's promo code. May be empty. Do not change after 'finished' status", null=True, on_delete=django.db.models.deletion.PROTECT, to='core.promocode', verbose_name='promo code'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='products',
            field=models.ManyToManyField(blank=True, help_text="Promotion's products", to='core.product', verbose_name='products'),
        ),
        migrations.AddField(
            model_name='stock',
            name='dealer',
            field=models.ForeignKey(help_text='Dealer', on_delete=django.db.models.deletion.CASCADE, to='core.dealer', verbose_name='dealer'),
        ),
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(help_text='Product', on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='core.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='products',
            field=models.ManyToManyField(blank=True, help_text="User's wishlisted products", to='core.product', verbose_name='products'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.OneToOneField(blank=True, help_text='User', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_related_wishlist', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterUniqueTogether(
            name='attributegrouptranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='attributetranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='attributevaluetranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AddConstraint(
            model_name='categoryattribute',
            constraint=models.UniqueConstraint(fields=('category', 'attribute'), name='unique_category_attribute'),
        ),
        migrations.AlterUniqueTogether(
            name='categorytranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AddIndex(
            model_name='orderproduct',
            index=django.contrib.postgres.indexes.GinIndex(fields=['notifications', 'attributes'], name='core_orderp_notific_cd27e9_gin'),
        ),
        migrations.AlterUniqueTogether(
            name='productattributetranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AddConstraint(
            model_name='productattributevalue',
            constraint=models.UniqueConstraint(fields=('product', 'attribute_value'), name='unique_product_attribute_value'),
        ),
        migrations.AlterUniqueTogether(
            name='producttagtranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='producttranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
