# Generated by Django 5.1.5 on 2025-03-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(help_text='name of this attribute', max_length=255, unique=True, verbose_name="attribute's name"),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name_ar_AR',
            field=models.CharField(help_text='name of this attribute', max_length=255, null=True, unique=True, verbose_name="attribute's name"),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name_cs_CZ',
            field=models.CharField(help_text='name of this attribute', max_length=255, null=True, unique=True, verbose_name="attribute's name"),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name_da_DK',
            field=models.CharField(help_text='name of this attribute', max_length=255, null=True, unique=True, verbose_name="attribute's name"),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name_de_DE',
            field=models.CharField(help_text='name of this attribute', max_length=255, null=True, unique=True, verbose_name="attribute's name"),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name_en_GB',
            field=models.CharField(help_text='name of this attribute', max_length=255, null=True, unique=True, verbose_name="attribute's name"),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name_en_US',
            field=models.CharField(help_text='name of this attribute', max_length=255, null=True, unique=True, verbose_name="attribute's name"),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name_es_ES',
            field=models.CharField(help_text='name of this attribute', max_length=255, null=True, unique=True, verbose_name="attribute's name"),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name_fr_FR',
            field=models.CharField(help_text='name of this attribute', max_length=255, null=True, unique=True, verbose_name="attribute's name"),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name_hi_IN',
            field=models.CharField(help_text='name of this attribute', max_length=255, null=True, unique=True, verbose_name="attribute's name"),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name_it_IT',
            field=models.CharField(help_text='name of this attribute', max_length=255, null=True, unique=True, verbose_name="attribute's name"),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name_ja_JP',
            field=models.CharField(help_text='name of this attribute', max_length=255, null=True, unique=True, verbose_name="attribute's name"),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name_kk_KZ',
            field=models.CharField(help_text='name of this attribute', max_length=255, null=True, unique=True, verbose_name="attribute's name"),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name_nl_NL',
            field=models.CharField(help_text='name of this attribute', max_length=255, null=True, unique=True, verbose_name="attribute's name"),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name_pl_PL',
            field=models.CharField(help_text='name of this attribute', max_length=255, null=True, unique=True, verbose_name="attribute's name"),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name_pt_BR',
            field=models.CharField(help_text='name of this attribute', max_length=255, null=True, unique=True, verbose_name="attribute's name"),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name_ro_RO',
            field=models.CharField(help_text='name of this attribute', max_length=255, null=True, unique=True, verbose_name="attribute's name"),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name_ru_RU',
            field=models.CharField(help_text='name of this attribute', max_length=255, null=True, unique=True, verbose_name="attribute's name"),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name_zh_hans',
            field=models.CharField(help_text='name of this attribute', max_length=255, null=True, unique=True, verbose_name="attribute's name"),
        ),
        migrations.AlterField(
            model_name='attributegroup',
            name='name',
            field=models.CharField(help_text="attribute group's name", max_length=255, unique=True, verbose_name="attribute group's name"),
        ),
        migrations.AlterField(
            model_name='attributegroup',
            name='name_ar_AR',
            field=models.CharField(help_text="attribute group's name", max_length=255, null=True, unique=True, verbose_name="attribute group's name"),
        ),
        migrations.AlterField(
            model_name='attributegroup',
            name='name_cs_CZ',
            field=models.CharField(help_text="attribute group's name", max_length=255, null=True, unique=True, verbose_name="attribute group's name"),
        ),
        migrations.AlterField(
            model_name='attributegroup',
            name='name_da_DK',
            field=models.CharField(help_text="attribute group's name", max_length=255, null=True, unique=True, verbose_name="attribute group's name"),
        ),
        migrations.AlterField(
            model_name='attributegroup',
            name='name_de_DE',
            field=models.CharField(help_text="attribute group's name", max_length=255, null=True, unique=True, verbose_name="attribute group's name"),
        ),
        migrations.AlterField(
            model_name='attributegroup',
            name='name_en_GB',
            field=models.CharField(help_text="attribute group's name", max_length=255, null=True, unique=True, verbose_name="attribute group's name"),
        ),
        migrations.AlterField(
            model_name='attributegroup',
            name='name_en_US',
            field=models.CharField(help_text="attribute group's name", max_length=255, null=True, unique=True, verbose_name="attribute group's name"),
        ),
        migrations.AlterField(
            model_name='attributegroup',
            name='name_es_ES',
            field=models.CharField(help_text="attribute group's name", max_length=255, null=True, unique=True, verbose_name="attribute group's name"),
        ),
        migrations.AlterField(
            model_name='attributegroup',
            name='name_fr_FR',
            field=models.CharField(help_text="attribute group's name", max_length=255, null=True, unique=True, verbose_name="attribute group's name"),
        ),
        migrations.AlterField(
            model_name='attributegroup',
            name='name_hi_IN',
            field=models.CharField(help_text="attribute group's name", max_length=255, null=True, unique=True, verbose_name="attribute group's name"),
        ),
        migrations.AlterField(
            model_name='attributegroup',
            name='name_it_IT',
            field=models.CharField(help_text="attribute group's name", max_length=255, null=True, unique=True, verbose_name="attribute group's name"),
        ),
        migrations.AlterField(
            model_name='attributegroup',
            name='name_ja_JP',
            field=models.CharField(help_text="attribute group's name", max_length=255, null=True, unique=True, verbose_name="attribute group's name"),
        ),
        migrations.AlterField(
            model_name='attributegroup',
            name='name_kk_KZ',
            field=models.CharField(help_text="attribute group's name", max_length=255, null=True, unique=True, verbose_name="attribute group's name"),
        ),
        migrations.AlterField(
            model_name='attributegroup',
            name='name_nl_NL',
            field=models.CharField(help_text="attribute group's name", max_length=255, null=True, unique=True, verbose_name="attribute group's name"),
        ),
        migrations.AlterField(
            model_name='attributegroup',
            name='name_pl_PL',
            field=models.CharField(help_text="attribute group's name", max_length=255, null=True, unique=True, verbose_name="attribute group's name"),
        ),
        migrations.AlterField(
            model_name='attributegroup',
            name='name_pt_BR',
            field=models.CharField(help_text="attribute group's name", max_length=255, null=True, unique=True, verbose_name="attribute group's name"),
        ),
        migrations.AlterField(
            model_name='attributegroup',
            name='name_ro_RO',
            field=models.CharField(help_text="attribute group's name", max_length=255, null=True, unique=True, verbose_name="attribute group's name"),
        ),
        migrations.AlterField(
            model_name='attributegroup',
            name='name_ru_RU',
            field=models.CharField(help_text="attribute group's name", max_length=255, null=True, unique=True, verbose_name="attribute group's name"),
        ),
        migrations.AlterField(
            model_name='attributegroup',
            name='name_zh_hans',
            field=models.CharField(help_text="attribute group's name", max_length=255, null=True, unique=True, verbose_name="attribute group's name"),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(help_text='name of this brand', max_length=255, unique=True, verbose_name='brand name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='provide a name for this category', max_length=255, unique=True, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ar_AR',
            field=models.CharField(help_text='provide a name for this category', max_length=255, null=True, unique=True, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_cs_CZ',
            field=models.CharField(help_text='provide a name for this category', max_length=255, null=True, unique=True, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_da_DK',
            field=models.CharField(help_text='provide a name for this category', max_length=255, null=True, unique=True, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_de_DE',
            field=models.CharField(help_text='provide a name for this category', max_length=255, null=True, unique=True, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en_GB',
            field=models.CharField(help_text='provide a name for this category', max_length=255, null=True, unique=True, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en_US',
            field=models.CharField(help_text='provide a name for this category', max_length=255, null=True, unique=True, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_es_ES',
            field=models.CharField(help_text='provide a name for this category', max_length=255, null=True, unique=True, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_fr_FR',
            field=models.CharField(help_text='provide a name for this category', max_length=255, null=True, unique=True, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_hi_IN',
            field=models.CharField(help_text='provide a name for this category', max_length=255, null=True, unique=True, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_it_IT',
            field=models.CharField(help_text='provide a name for this category', max_length=255, null=True, unique=True, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ja_JP',
            field=models.CharField(help_text='provide a name for this category', max_length=255, null=True, unique=True, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_kk_KZ',
            field=models.CharField(help_text='provide a name for this category', max_length=255, null=True, unique=True, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_nl_NL',
            field=models.CharField(help_text='provide a name for this category', max_length=255, null=True, unique=True, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_pl_PL',
            field=models.CharField(help_text='provide a name for this category', max_length=255, null=True, unique=True, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_pt_BR',
            field=models.CharField(help_text='provide a name for this category', max_length=255, null=True, unique=True, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ro_RO',
            field=models.CharField(help_text='provide a name for this category', max_length=255, null=True, unique=True, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru_RU',
            field=models.CharField(help_text='provide a name for this category', max_length=255, null=True, unique=True, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_zh_hans',
            field=models.CharField(help_text='provide a name for this category', max_length=255, null=True, unique=True, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='provide a clear identifying name for the product', max_length=255, unique=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ar_AR',
            field=models.CharField(help_text='provide a clear identifying name for the product', max_length=255, null=True, unique=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_cs_CZ',
            field=models.CharField(help_text='provide a clear identifying name for the product', max_length=255, null=True, unique=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_da_DK',
            field=models.CharField(help_text='provide a clear identifying name for the product', max_length=255, null=True, unique=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_de_DE',
            field=models.CharField(help_text='provide a clear identifying name for the product', max_length=255, null=True, unique=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en_GB',
            field=models.CharField(help_text='provide a clear identifying name for the product', max_length=255, null=True, unique=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en_US',
            field=models.CharField(help_text='provide a clear identifying name for the product', max_length=255, null=True, unique=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_es_ES',
            field=models.CharField(help_text='provide a clear identifying name for the product', max_length=255, null=True, unique=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_fr_FR',
            field=models.CharField(help_text='provide a clear identifying name for the product', max_length=255, null=True, unique=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_hi_IN',
            field=models.CharField(help_text='provide a clear identifying name for the product', max_length=255, null=True, unique=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_it_IT',
            field=models.CharField(help_text='provide a clear identifying name for the product', max_length=255, null=True, unique=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ja_JP',
            field=models.CharField(help_text='provide a clear identifying name for the product', max_length=255, null=True, unique=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_kk_KZ',
            field=models.CharField(help_text='provide a clear identifying name for the product', max_length=255, null=True, unique=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_nl_NL',
            field=models.CharField(help_text='provide a clear identifying name for the product', max_length=255, null=True, unique=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_pl_PL',
            field=models.CharField(help_text='provide a clear identifying name for the product', max_length=255, null=True, unique=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_pt_BR',
            field=models.CharField(help_text='provide a clear identifying name for the product', max_length=255, null=True, unique=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ro_RO',
            field=models.CharField(help_text='provide a clear identifying name for the product', max_length=255, null=True, unique=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ru_RU',
            field=models.CharField(help_text='provide a clear identifying name for the product', max_length=255, null=True, unique=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_zh_hans',
            field=models.CharField(help_text='provide a clear identifying name for the product', max_length=255, null=True, unique=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='name',
            field=models.CharField(help_text='user-friendly name for the product tag', max_length=255, unique=True, verbose_name='tag display name'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='name_ar_AR',
            field=models.CharField(help_text='user-friendly name for the product tag', max_length=255, null=True, unique=True, verbose_name='tag display name'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='name_cs_CZ',
            field=models.CharField(help_text='user-friendly name for the product tag', max_length=255, null=True, unique=True, verbose_name='tag display name'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='name_da_DK',
            field=models.CharField(help_text='user-friendly name for the product tag', max_length=255, null=True, unique=True, verbose_name='tag display name'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='name_de_DE',
            field=models.CharField(help_text='user-friendly name for the product tag', max_length=255, null=True, unique=True, verbose_name='tag display name'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='name_en_GB',
            field=models.CharField(help_text='user-friendly name for the product tag', max_length=255, null=True, unique=True, verbose_name='tag display name'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='name_en_US',
            field=models.CharField(help_text='user-friendly name for the product tag', max_length=255, null=True, unique=True, verbose_name='tag display name'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='name_es_ES',
            field=models.CharField(help_text='user-friendly name for the product tag', max_length=255, null=True, unique=True, verbose_name='tag display name'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='name_fr_FR',
            field=models.CharField(help_text='user-friendly name for the product tag', max_length=255, null=True, unique=True, verbose_name='tag display name'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='name_hi_IN',
            field=models.CharField(help_text='user-friendly name for the product tag', max_length=255, null=True, unique=True, verbose_name='tag display name'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='name_it_IT',
            field=models.CharField(help_text='user-friendly name for the product tag', max_length=255, null=True, unique=True, verbose_name='tag display name'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='name_ja_JP',
            field=models.CharField(help_text='user-friendly name for the product tag', max_length=255, null=True, unique=True, verbose_name='tag display name'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='name_kk_KZ',
            field=models.CharField(help_text='user-friendly name for the product tag', max_length=255, null=True, unique=True, verbose_name='tag display name'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='name_nl_NL',
            field=models.CharField(help_text='user-friendly name for the product tag', max_length=255, null=True, unique=True, verbose_name='tag display name'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='name_pl_PL',
            field=models.CharField(help_text='user-friendly name for the product tag', max_length=255, null=True, unique=True, verbose_name='tag display name'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='name_pt_BR',
            field=models.CharField(help_text='user-friendly name for the product tag', max_length=255, null=True, unique=True, verbose_name='tag display name'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='name_ro_RO',
            field=models.CharField(help_text='user-friendly name for the product tag', max_length=255, null=True, unique=True, verbose_name='tag display name'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='name_ru_RU',
            field=models.CharField(help_text='user-friendly name for the product tag', max_length=255, null=True, unique=True, verbose_name='tag display name'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='name_zh_hans',
            field=models.CharField(help_text='user-friendly name for the product tag', max_length=255, null=True, unique=True, verbose_name='tag display name'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(help_text='name of this vendor', max_length=255, unique=True, verbose_name='vendor name'),
        ),
    ]
