# Generated by Django 5.1.5 on 2025-03-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_attribute_name_alter_attribute_name_ar_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='provide a clear identifying name for the product', max_length=255, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ar_AR',
            field=models.CharField(help_text='provide a clear identifying name for the product', max_length=255, null=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_cs_CZ',
            field=models.CharField(help_text='provide a clear identifying name for the product', max_length=255, null=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_da_DK',
            field=models.CharField(help_text='provide a clear identifying name for the product', max_length=255, null=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_de_DE',
            field=models.CharField(help_text='provide a clear identifying name for the product', max_length=255, null=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en_GB',
            field=models.CharField(help_text='provide a clear identifying name for the product', max_length=255, null=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en_US',
            field=models.CharField(help_text='provide a clear identifying name for the product', max_length=255, null=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_es_ES',
            field=models.CharField(help_text='provide a clear identifying name for the product', max_length=255, null=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_fr_FR',
            field=models.CharField(help_text='provide a clear identifying name for the product', max_length=255, null=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_hi_IN',
            field=models.CharField(help_text='provide a clear identifying name for the product', max_length=255, null=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_it_IT',
            field=models.CharField(help_text='provide a clear identifying name for the product', max_length=255, null=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ja_JP',
            field=models.CharField(help_text='provide a clear identifying name for the product', max_length=255, null=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_kk_KZ',
            field=models.CharField(help_text='provide a clear identifying name for the product', max_length=255, null=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_nl_NL',
            field=models.CharField(help_text='provide a clear identifying name for the product', max_length=255, null=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_pl_PL',
            field=models.CharField(help_text='provide a clear identifying name for the product', max_length=255, null=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_pt_BR',
            field=models.CharField(help_text='provide a clear identifying name for the product', max_length=255, null=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ro_RO',
            field=models.CharField(help_text='provide a clear identifying name for the product', max_length=255, null=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ru_RU',
            field=models.CharField(help_text='provide a clear identifying name for the product', max_length=255, null=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_zh_hans',
            field=models.CharField(help_text='provide a clear identifying name for the product', max_length=255, null=True, verbose_name='product name'),
        ),
    ]
