# Generated by Django 5.0.8 on 2024-09-02 03:58

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='attributes',
            field=models.JSONField(blank=True, help_text="Order-product's notifications. Displayed to user's on the storefront", null=True, verbose_name='notifications'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='Image', upload_to=core.models.ProductImage.get_product_uuid_as_path, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='priority',
            field=models.IntegerField(default=1, help_text="Image's priority. 1 means the first displayed image", validators=[django.core.validators.MinValueValidator(1)], verbose_name='priority'),
        ),
    ]
