# Generated by Django 5.0.8 on 2024-09-02 04:17

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_orderproduct_attributes_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='Image', upload_to=core.models.ProductImage.get_product_uuid_as_path, verbose_name='image'),
        ),
    ]
