# Generated by Django 5.1.5 on 2025-03-24 14:04

from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='upload an image representing this category', null=True,
                                    upload_to='categories/',
                                    validators=[core.validators.validate_category_image_dimensions],
                                    verbose_name='category image'),
        ),
    ]
