# Generated by Django 5.1.8 on 2025-04-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_documentary'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='partnumber',
            field=models.CharField(default=None, help_text='part number for this product', null=True, unique=True, verbose_name='part number'),
        ),
    ]
