# Generated by Django 5.1.8 on 2025-04-18 11:34

from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0010_product_partnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='big_logo',
            field=models.ImageField(blank=True, help_text='upload a big logo representing this brand', null=True,
                                    upload_to='brands/',
                                    validators=[core.validators.validate_category_image_dimensions],
                                    verbose_name='brand big image'),
        ),
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, help_text='add a detailed description of the brand', null=True,
                                   verbose_name='brand description'),
        ),
        migrations.AddField(
            model_name='brand',
            name='description_ar_AR',
            field=models.TextField(blank=True, help_text='add a detailed description of the brand', null=True,
                                   verbose_name='brand description'),
        ),
        migrations.AddField(
            model_name='brand',
            name='description_cs_CZ',
            field=models.TextField(blank=True, help_text='add a detailed description of the brand', null=True,
                                   verbose_name='brand description'),
        ),
        migrations.AddField(
            model_name='brand',
            name='description_da_DK',
            field=models.TextField(blank=True, help_text='add a detailed description of the brand', null=True,
                                   verbose_name='brand description'),
        ),
        migrations.AddField(
            model_name='brand',
            name='description_de_DE',
            field=models.TextField(blank=True, help_text='add a detailed description of the brand', null=True,
                                   verbose_name='brand description'),
        ),
        migrations.AddField(
            model_name='brand',
            name='description_en_GB',
            field=models.TextField(blank=True, help_text='add a detailed description of the brand', null=True,
                                   verbose_name='brand description'),
        ),
        migrations.AddField(
            model_name='brand',
            name='description_en_US',
            field=models.TextField(blank=True, help_text='add a detailed description of the brand', null=True,
                                   verbose_name='brand description'),
        ),
        migrations.AddField(
            model_name='brand',
            name='description_es_ES',
            field=models.TextField(blank=True, help_text='add a detailed description of the brand', null=True,
                                   verbose_name='brand description'),
        ),
        migrations.AddField(
            model_name='brand',
            name='description_fr_FR',
            field=models.TextField(blank=True, help_text='add a detailed description of the brand', null=True,
                                   verbose_name='brand description'),
        ),
        migrations.AddField(
            model_name='brand',
            name='description_hi_IN',
            field=models.TextField(blank=True, help_text='add a detailed description of the brand', null=True,
                                   verbose_name='brand description'),
        ),
        migrations.AddField(
            model_name='brand',
            name='description_it_IT',
            field=models.TextField(blank=True, help_text='add a detailed description of the brand', null=True,
                                   verbose_name='brand description'),
        ),
        migrations.AddField(
            model_name='brand',
            name='description_ja_JP',
            field=models.TextField(blank=True, help_text='add a detailed description of the brand', null=True,
                                   verbose_name='brand description'),
        ),
        migrations.AddField(
            model_name='brand',
            name='description_kk_KZ',
            field=models.TextField(blank=True, help_text='add a detailed description of the brand', null=True,
                                   verbose_name='brand description'),
        ),
        migrations.AddField(
            model_name='brand',
            name='description_nl_NL',
            field=models.TextField(blank=True, help_text='add a detailed description of the brand', null=True,
                                   verbose_name='brand description'),
        ),
        migrations.AddField(
            model_name='brand',
            name='description_pl_PL',
            field=models.TextField(blank=True, help_text='add a detailed description of the brand', null=True,
                                   verbose_name='brand description'),
        ),
        migrations.AddField(
            model_name='brand',
            name='description_pt_BR',
            field=models.TextField(blank=True, help_text='add a detailed description of the brand', null=True,
                                   verbose_name='brand description'),
        ),
        migrations.AddField(
            model_name='brand',
            name='description_ro_RO',
            field=models.TextField(blank=True, help_text='add a detailed description of the brand', null=True,
                                   verbose_name='brand description'),
        ),
        migrations.AddField(
            model_name='brand',
            name='description_ru_RU',
            field=models.TextField(blank=True, help_text='add a detailed description of the brand', null=True,
                                   verbose_name='brand description'),
        ),
        migrations.AddField(
            model_name='brand',
            name='description_zh_hans',
            field=models.TextField(blank=True, help_text='add a detailed description of the brand', null=True,
                                   verbose_name='brand description'),
        ),
        migrations.AddField(
            model_name='brand',
            name='small_logo',
            field=models.ImageField(blank=True, help_text='upload a logo representing this brand', null=True,
                                    upload_to='brands/',
                                    validators=[core.validators.validate_category_image_dimensions],
                                    verbose_name='brand small image'),
        ),
    ]
