# Generated by Django 5.1.8 on 2025-04-30 13:42

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(allow_unicode=True, blank=True, editable=False, populate_from=('uuid', 'category.name', 'brand.name', 'name'), unique=True),
        ),
    ]
