# Generated by Django 5.1.8 on 2025-05-06 13:58

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_order_human_readable_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='human_readable_id',
            field=models.CharField(default=core.utils.generate_human_readable_id, help_text='a human-readable identifier for the order', max_length=6, unique=True, verbose_name='human readable id'),
        ),
    ]
