# Generated by Django 5.2 on 2025-05-20 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0019_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, help_text='the billing address used for this order', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, related_name='billing_address_order',
                                    to='core.address', verbose_name='billing address'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, help_text='the shipping address used for this order', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address_order',
                                    to='core.address', verbose_name='shipping address'),
        ),
    ]
