# Generated by Django 5.2 on 2025-05-21 09:35

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0021_rename_name_ar_ar_attribute_name_ar_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(allow_unicode=True, blank=True, editable=False, null=True,
                                                            populate_from=('uuid', 'name'), unique=True),
        ),
    ]
