# Generated by Django 5.2 on 2025-05-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0022_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_line',
            field=models.TextField(blank=True, help_text='address line for the customer', null=True,
                                   verbose_name='address line'),
        ),
    ]
