# Generated by Django 5.2 on 2025-05-19 11:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='api_response',
            field=models.JSONField(blank=True, help_text='stored JSON response from the geocoding service', null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True,
                                                                 help_text='geolocation point: (longitude, latitude)',
                                                                 null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='address',
            name='raw_data',
            field=models.JSONField(blank=True, help_text='full JSON response from geocoder for this address',
                                   null=True),
        ),
    ]
