# Generated by Django 5.2 on 2025-05-19 14:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('geo', '0002_alter_address_api_response_alter_address_location_and_more'),
    ]

    operations = [
    ]
