# Generated by Django 5.1.5 on 2025-03-10 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0013_alter_city_options_alternativename_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'address', 'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'city', 'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='continent',
            options={'verbose_name': 'continent', 'verbose_name_plural': 'continents'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'district', 'verbose_name_plural': 'districts'},
        ),
        migrations.AlterModelOptions(
            name='postalcode',
            options={'verbose_name': 'postal code', 'verbose_name_plural': 'postal codes'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'region', 'verbose_name_plural': 'regions'},
        ),
        migrations.AlterModelOptions(
            name='subregion',
            options={'verbose_name': 'subregion', 'verbose_name_plural': 'subregions'},
        ),
    ]
